apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: k8s-project
  template:
    metadata:
      labels:
        app: k8s-project
    spec:
      containers:
      - name: project-k8s
        image: ashishdubey195/k8s-project:latest
        ports:
        - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-project-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
